// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXD2fWL7kT1-zQAl6zY-aNCv6KCtwbCr4',
    appId: '1:887427866232:web:a97faddb88088bd3da578d',
    messagingSenderId: '887427866232',
    projectId: 'authentication-76e60',
    authDomain: 'authentication-76e60.firebaseapp.com',
    storageBucket: 'authentication-76e60.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6pfFG1tm1Or4tiZHQ39jSSNlFFdM18-c',
    appId: '1:887427866232:android:442e5bf212a341b6da578d',
    messagingSenderId: '887427866232',
    projectId: 'authentication-76e60',
    storageBucket: 'authentication-76e60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa6MujW85utpwKM-gn93_f_ezXie9JW38',
    appId: '1:887427866232:ios:c641eb69ac781069da578d',
    messagingSenderId: '887427866232',
    projectId: 'authentication-76e60',
    storageBucket: 'authentication-76e60.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa6MujW85utpwKM-gn93_f_ezXie9JW38',
    appId: '1:887427866232:ios:c641eb69ac781069da578d',
    messagingSenderId: '887427866232',
    projectId: 'authentication-76e60',
    storageBucket: 'authentication-76e60.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXD2fWL7kT1-zQAl6zY-aNCv6KCtwbCr4',
    appId: '1:887427866232:web:94ed748ef21f7e1ada578d',
    messagingSenderId: '887427866232',
    projectId: 'authentication-76e60',
    authDomain: 'authentication-76e60.firebaseapp.com',
    storageBucket: 'authentication-76e60.appspot.com',
  );
}
